# 默认使用配置
#spring:
#  profiles:
#    active: dev

server:
  port: 8080

#公共配置与profiles选择无关
mybatis:
  # 注意：对应实体类的路径
  type-aliases-package: com.xiaozhuanglt.mitutucute.springboot.dal.model
  #注意：一定要对应mapper映射xml文件的所在路
  mapper-locations: classpath: mapper/**/*.xml


# 开发配置
spring:
  profiles:

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/mitutucue?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      read-only: false
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 180000
      maximum-pool-size: 15

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
